#通过 workflow_dispatch 触发，cron任务部署在云函数
name: test

on:
  workflow_dispatch:

jobs:
  start:
    name: Run your tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I just ran all your tests!"
  
