#通过 workflow_dispatch 触发，cron任务部署在云函数
name: test

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      
      run: |
        print('hello')
#以下省略
